version: "3"

services:

  ####################### Frontend Definition #######################
  frontend:
    image: bcros_frontend
    container_name: bcros_frontend
    build:
      context: coops-ui
    command: ["npm", "run", "serve", "--disable-host-check","--host 0.0.0.0", "--disableHostCheck", "true" ]
    volumes:
      - ./coops-ui/src:/opt/app/src
      - ./coops-ui/tests:/opt/app/tests
      - ./coops-ui/public:/opt/app/public
    ports:
      - 8080:8080
#    depends_on:
#      - backend
    env_file: ./coops-ui/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - bcros
  ####################### Caddy Definition #######################
  caddy_proxy:
    image: bcros_proxy
    container_name: bcros_proxy
    build:
      context: Caddy
    ports:
      - 2015:2015
    networks:
      - bcros
####################### Networks Definition #######################
networks:
  bcros:
    driver: "bridge"

####################### Volumes Definition #######################
volumes:
  postgres-data: